<?php

namespace Proxies\__CG__\Zogs\WorldBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class State extends \Zogs\WorldBundle\Entity\State implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'id', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'char_code', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'ufi', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'uni', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'cc1', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'dsg', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'adm_parent', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'adm_code', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'nt', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'lang', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'shortform', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'fullname', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'name', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'characters', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'level');
        }

        return array('__isInitialized__', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'id', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'char_code', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'ufi', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'uni', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'cc1', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'dsg', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'adm_parent', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'adm_code', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'nt', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'lang', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'shortform', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'fullname', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'name', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'characters', '' . "\0" . 'Zogs\\WorldBundle\\Entity\\State' . "\0" . 'level');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (State $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getLevel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLevel', array());

        return parent::getLevel();
    }

    /**
     * {@inheritDoc}
     */
    public function exist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'exist', array());

        return parent::exist();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCharCode($charCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCharCode', array($charCode));

        return parent::setCharCode($charCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getCharCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCharCode', array());

        return parent::getCharCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setUfi($ufi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUfi', array($ufi));

        return parent::setUfi($ufi);
    }

    /**
     * {@inheritDoc}
     */
    public function getUfi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUfi', array());

        return parent::getUfi();
    }

    /**
     * {@inheritDoc}
     */
    public function setUni($uni)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUni', array($uni));

        return parent::setUni($uni);
    }

    /**
     * {@inheritDoc}
     */
    public function getUni()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUni', array());

        return parent::getUni();
    }

    /**
     * {@inheritDoc}
     */
    public function setCc1($cc1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCc1', array($cc1));

        return parent::setCc1($cc1);
    }

    /**
     * {@inheritDoc}
     */
    public function getCc1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCc1', array());

        return parent::getCc1();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsg($dsg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsg', array($dsg));

        return parent::setDsg($dsg);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsg', array());

        return parent::getDsg();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdmParent($admParent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdmParent', array($admParent));

        return parent::setAdmParent($admParent);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdmParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdmParent', array());

        return parent::getAdmParent();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdmCode($admCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdmCode', array($admCode));

        return parent::setAdmCode($admCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdmCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdmCode', array());

        return parent::getAdmCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setNt($nt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNt', array($nt));

        return parent::setNt($nt);
    }

    /**
     * {@inheritDoc}
     */
    public function getNt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNt', array());

        return parent::getNt();
    }

    /**
     * {@inheritDoc}
     */
    public function setLang($lang)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLang', array($lang));

        return parent::setLang($lang);
    }

    /**
     * {@inheritDoc}
     */
    public function getLang()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLang', array());

        return parent::getLang();
    }

    /**
     * {@inheritDoc}
     */
    public function setShortform($shortform)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShortform', array($shortform));

        return parent::setShortform($shortform);
    }

    /**
     * {@inheritDoc}
     */
    public function getShortform()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShortform', array());

        return parent::getShortform();
    }

    /**
     * {@inheritDoc}
     */
    public function setFullname($fullname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFullname', array($fullname));

        return parent::setFullname($fullname);
    }

    /**
     * {@inheritDoc}
     */
    public function getFullname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullname', array());

        return parent::getFullname();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCharacters($characters)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCharacters', array($characters));

        return parent::setCharacters($characters);
    }

    /**
     * {@inheritDoc}
     */
    public function getCharacters()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCharacters', array());

        return parent::getCharacters();
    }

}
