crc_reserv:
    resource: "@CrcReservBundle/Resources/config/routing.yml"
    prefix:   /

#Oauth routes must appears first
hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /oauth-login
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /oauth-connect
facebook_login:
    pattern: /login/check-facebook

#Custom Bundle routes
zogs_user:
    resource: "@ZogsUserBundle/Resources/config/routing.yml"
    prefix:   /

zogs_utils:
    resource: "@ZogsUtilsBundle/Resources/config/routing.yml"
    prefix:   /utils

zogs_page:
    resource: "@ZogsPageBundle/Resources/config/routing.yml"
    prefix:   /

zogs_contact:
    resource: "@ZogsContactBundle/Resources/config/routing.yml"
    prefix:   /

zogs_mailer:
    resource: "@ZogsMailerBundle/Resources/config/routing.yml"
    prefix:   /zmailer

zogs_flash:
    resource: "@ZogsFlashBundle/Resources/config/routing.yml"
    prefix:   /flashbag

zogs_world:
    resource: "@ZogsWorldBundle/Resources/config/routing.yml"
    prefix:   /world

#Vendor routes
fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

#Homepage app
homepage:
    path: /homepage
    defaults: { _controller: ZogsPageBundle:Page:homepage }
    resource:     

#Redirect / to homepage
root:
    pattern: /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: crc_reserv_home, permanent: true }

#Sonata admin
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

#Removing trailing / in url 
rm_trailing_slash:
    path: /{url}
    defaults: { _controller: ZogsUtilsBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET|POST]

