dbtool_convert_index:
    path: /convert/index
    defaults: { _controller: ZogsDatabaseBundle:Convert:index }

dbtool_convert_one:
    path:     /one
    defaults: { _controller: ZogsDatabaseBundle:Convert:convertOne }
    requirements:
        _method: GET

dbtool_convert_all:
    path:     /all
    defaults: { _controller: ZogsDatabaseBundle:Convert:convertAll }

dbtool_purge:
    path:     /purge
    defaults: { _controller: ZogsDatabaseBundle:Convert:purge }

