parameters:
#    ws_convert_sql.example.class: Ws\ConvertSQLBundle\Example

services:
#    ws_convert_sql.example:
#        class: %ws_convert_sql.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    dbtool.table_converter:
        class: Zogs\DatabaseToolBundle\Converter\Converter
        arguments: [null,@doctrine.orm.entity_manager,@service_container]

    dbtool.table_purger:
        class: Zogs\DatabaseToolBundle\Converter\Purger
        arguments: [@doctrine.orm.entity_manager]