services:
    sonata.admin.zogs.cron:
        class: Zogs\CronBundle\Admin\CronAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "System", label: "Cron" }
        arguments:
            - ~
            - Zogs\CronBundle\Entity\CronTask
            - ~
        calls:
            - [ setTranslationDomain, [AcmeDemoBundle]]
