<?php

namespace Proxies\__CG__\Zogs\MailerBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Settings extends \Zogs\MailerBundle\Entity\Settings implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Zogs\\MailerBundle\\Entity\\Settings' . "\0" . 'id', '' . "\0" . 'Zogs\\MailerBundle\\Entity\\Settings' . "\0" . 'event_confirmed', '' . "\0" . 'Zogs\\MailerBundle\\Entity\\Settings' . "\0" . 'event_canceled', '' . "\0" . 'Zogs\\MailerBundle\\Entity\\Settings' . "\0" . 'event_changed', '' . "\0" . 'Zogs\\MailerBundle\\Entity\\Settings' . "\0" . 'event_opinion', '' . "\0" . 'Zogs\\MailerBundle\\Entity\\Settings' . "\0" . 'event_user_question', '' . "\0" . 'Zogs\\MailerBundle\\Entity\\Settings' . "\0" . 'event_organizer_answer', '' . "\0" . 'Zogs\\MailerBundle\\Entity\\Settings' . "\0" . 'event_add_participation', '' . "\0" . 'Zogs\\MailerBundle\\Entity\\Settings' . "\0" . 'event_cancel_participation');
        }

        return array('__isInitialized__', '' . "\0" . 'Zogs\\MailerBundle\\Entity\\Settings' . "\0" . 'id', '' . "\0" . 'Zogs\\MailerBundle\\Entity\\Settings' . "\0" . 'event_confirmed', '' . "\0" . 'Zogs\\MailerBundle\\Entity\\Settings' . "\0" . 'event_canceled', '' . "\0" . 'Zogs\\MailerBundle\\Entity\\Settings' . "\0" . 'event_changed', '' . "\0" . 'Zogs\\MailerBundle\\Entity\\Settings' . "\0" . 'event_opinion', '' . "\0" . 'Zogs\\MailerBundle\\Entity\\Settings' . "\0" . 'event_user_question', '' . "\0" . 'Zogs\\MailerBundle\\Entity\\Settings' . "\0" . 'event_organizer_answer', '' . "\0" . 'Zogs\\MailerBundle\\Entity\\Settings' . "\0" . 'event_add_participation', '' . "\0" . 'Zogs\\MailerBundle\\Entity\\Settings' . "\0" . 'event_cancel_participation');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Settings $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function isAuthorized($setting)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAuthorized', array($setting));

        return parent::isAuthorized($setting);
    }

    /**
     * {@inheritDoc}
     */
    public function setEventConfirmed($eventConfirmed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventConfirmed', array($eventConfirmed));

        return parent::setEventConfirmed($eventConfirmed);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventConfirmed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventConfirmed', array());

        return parent::getEventConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventCanceled($eventCanceled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventCanceled', array($eventCanceled));

        return parent::setEventCanceled($eventCanceled);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventCanceled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventCanceled', array());

        return parent::getEventCanceled();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventChanged($eventChanged)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventChanged', array($eventChanged));

        return parent::setEventChanged($eventChanged);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventChanged()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventChanged', array());

        return parent::getEventChanged();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventOpinion($eventOpinion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventOpinion', array($eventOpinion));

        return parent::setEventOpinion($eventOpinion);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventOpinion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventOpinion', array());

        return parent::getEventOpinion();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventUserQuestion($eventUserQuestion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventUserQuestion', array($eventUserQuestion));

        return parent::setEventUserQuestion($eventUserQuestion);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventUserQuestion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventUserQuestion', array());

        return parent::getEventUserQuestion();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventOrganizerAnswer($eventOrganizerAnswer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventOrganizerAnswer', array($eventOrganizerAnswer));

        return parent::setEventOrganizerAnswer($eventOrganizerAnswer);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventOrganizerAnswer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventOrganizerAnswer', array());

        return parent::getEventOrganizerAnswer();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventAddParticipation($eventAddParticipation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventAddParticipation', array($eventAddParticipation));

        return parent::setEventAddParticipation($eventAddParticipation);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventAddParticipation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventAddParticipation', array());

        return parent::getEventAddParticipation();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventCancelParticipation($eventCancelParticipation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventCancelParticipation', array($eventCancelParticipation));

        return parent::setEventCancelParticipation($eventCancelParticipation);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventCancelParticipation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventCancelParticipation', array());

        return parent::getEventCancelParticipation();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

}
