<?php

namespace Crc\ReservBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Crc\ReservBundle\Entity\Department;
use Zogs\UserBundle\Entity\User;
/**
 * ReservRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends EntityRepository
{
	public function findConfirmedByDepartment(Department $department)
	{
		$qb = $this->createQueryBuilder('r');
		$qb->select('r')
			->andWhere('r.confirmed = :confirmed')->setParameter('confirmed',true)
			->andWhere('r.department = :department')->setParameter('department',$department)
			->andWhere('r.active = :active')->setParameter('active',true)
			->andWhere($qb->expr()->gte('DATE(r.date_end)','DATE(CURRENT_DATE())'))
			;

		return $qb->getQuery()->getResult();
	}

	public function findActiveByUser(User $user)
	{
		$qb = $this->createQueryBuilder('r');
		$qb->select('r')
			->andWhere('r.user = :user')->setParameter('user',$user)
			->andWhere('r.active = :active')->setParameter('active',true)
			->andWhere($qb->expr()->gte('DATE(r.date_end)','DATE(CURRENT_DATE())'))
			;

		return $qb->getQuery()->getResult();
	}

	public function findByIncomingBeginDate($nbdays)
	{
		$qb = $this->createQueryBuilder('r');
		$qb->select('r')
			->where('r.confirmed = :confirmed')->setParameter('confirmed',true)
			->andWhere('r.active = :active')->setParameter('active',false)
			->andWhere($qb->expr()->lte('r.date_begin',"DATE_ADD(CURRENT_DATE(), $nbdays, 'day')"))
			;

		return $qb->getQuery()->getResult();
	}

	public function findByIncomingEndDate($nbdays)
	{
		$qb = $this->createQueryBuilder('r');
		$qb->select('r')
			->where('r.confirmed = :confirmed')->setParameter('confirmed',true)
			->andWhere('r.active = :active')->setParameter('active',false)
			->andWhere($qb->expr()->lte('r.date_end',"DATE_ADD(CURRENT_DATE(), $nbdays, 'day')"))
			;

		return $qb->getQuery()->getResult();
	}
}
